### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by jwstric2** [jscep/jester#8]
1.  Need to remove org.apache.common.* code, Base64 and Base64 encoders.  Conflicts with class resolution.  See this at http://stackoverflow.com/questions/2047706/apache-commons-codec-with-android-could-not-find-method, links to the android bug too.

2. apache http client, had to port in a compiled android specific client.  I "believe" we may be able to leverage and use the pure java httpurlconnection (http://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html), would need to investigate this but this would port fine for both.  This would be longer

3.  Pulled in spongy castle for the decoder for android.  need to rip out bouncy code as it conflicts with android paths.

Other notes:

1.  Need a min of adk 16 (android 4.1) support for native tls 1.2.  If Spongy Castle (well Bouncy really) implements a TLS 1.2 or maybe even has now we could use this (load provider up dynamically or look at using light APIs)

2.  Added a socket factory to set socket to tls1.2 support.  Seems to be a problem in android where ssl context is 1.2 but sockets still be created with default 1.0 handshake.  Something like below was added to the http client:

I plan on having a couple push requests for these items in 1 by 1; minus the httpclient overhaul which would be a major version jump.  Would like feedback from the community on these changes first.

**Comment by AshiqKony** [comment]
is jscep csr generaion ported for android ?? I need some help on this

**Comment by seize-the-dave** [comment]
Is this meant to be in the jscep project?

**Comment by AshiqKony** [comment]
Anything is fine.I just need a way to generate a csr in the android
application..

**Comment by WesBunton** [comment]
AshiqKony - I know this tread is stale, but I could help you do CSR generation within Android. You need to implement the Spongy Castle library to do it easily.

**Comment by seize-the-dave** [comment]
Hi Wes,

I'm not looking to do any work on this project.  If you want to carry it on
I'd be happy to transfer it to you.

Dave
