### ISSUE TITLE
EstClienLibestIT Time Out

### ISSUE THREAD

**Issue by ragemachinest** [jscep/jester#9]
When running "mvn clean install" I consistently get an error:

testObtainCaCertificates(org.jscep.jester.EstClientLibestIT)  Time elapsed: 30.618 sec  <<< ERROR!
org.apache.http.conn.ConnectTimeoutException: Connect to ec2-54-204-91-178.compute-1.amazonaws.com:8443 [ec2-54-204-91-178.compute-1.amazonaws.com/54.204.91.178] failed: connect timed out

After editing EstClientLibestIT.java to point to "testrfc7030.cisco.com:8443" the error resolved itself.

**Comment by seize-the-dave** [comment]
I've updated the integration test to point to the Cisco endpoint.  I should mentioned that this project is mothballed, but feel free to do with it what you wish!
